-- UZUPELNIENIE TABELI Address
insert into Address (city, street) values ('Lillehammer', '676 Independence Trail');
insert into Address (city, street) values ('Évry', '61468 Carpenter Plaza');
insert into Address (city, street) values ('Bulod', '793 Granby Terrace');
insert into Address (city, street) values ('Castro Daire', '2533 Erie Center');
insert into Address (city, street) values ('Horokhiv', '392 Trailsway Circle');
insert into Address (city, street) values ('Buta Ranquil', '9488 Farmco Street');
insert into Address (city, street) values ('Hendala', '55985 Thackeray Road');
insert into Address (city, street) values ('Savonlinna', '07 Sundown Street');
insert into Address (city, street) values ('Laoliangcang', '69097 Esker Alley');
insert into Address (city, street) values ('Kemisē', '32 Ilene Road');
insert into Address (city, street) values ('Buenaventura', '0131 Bluestem Lane');
insert into Address (city, street) values ('Brongkah', '0230 Golf Plaza');
insert into Address (city, street) values ('Granada', '9438 South Way');
insert into Address (city, street) values ('Hot', '94462 Menomonie Plaza');
insert into Address (city, street) values ('Baishui', '30136 Loftsgordon Point');
insert into Address (city, street) values ('Eshan', '68 Anthes Point');
insert into Address (city, street) values ('Oulmes', '243 Ronald Regan Trail');
insert into Address (city, street) values ('Keli', '46 Southridge Trail');
insert into Address (city, street) values ('Khānpur', '60 Melrose Junction');
insert into Address (city, street) values ('Leuwibuleud', '7 Fairfield Terrace');
insert into Address (city, street) values ('Sofiyivka', '3 Marquette Park');
insert into Address (city, street) values ('Visaginas', '2 Crescent Oaks Lane');
insert into Address (city, street) values ('Huntington', '407 Bartillon Trail');
insert into Address (city, street) values ('Kamālia', '520 Graceland Center');
insert into Address (city, street) values ('Wolowiro', '87364 Lakewood Gardens Center');
insert into Address (city, street) values ('São Domingos', '94 Corben Center');
insert into Address (city, street) values ('Custódia', '13745 Sullivan Junction');
insert into Address (city, street) values ('Navashino', '94 Fieldstone Alley');
insert into Address (city, street) values ('Las Varas', '3830 Lunder Street');
insert into Address (city, street) values ('Chonglou', '01617 Express Trail');
insert into Address (city, street) values ('Słupno', '23351 Vera Place');
insert into Address (city, street) values ('Magisterial', '0667 Derek Alley');
insert into Address (city, street) values ('Payxambabazar', '0283 3rd Place');
insert into Address (city, street) values ('Wujing', '729 Forest Drive');
insert into Address (city, street) values ('Cholpon-Ata', '80 4th Terrace');
insert into Address (city, street) values ('Dallas', '01 Fuller Trail');
insert into Address (city, street) values ('Rybatskoye', '6 Burrows Park');
insert into Address (city, street) values ('Pangai', '58 Summerview Court');
insert into Address (city, street) values ('Brak', '83 Leroy Alley');
insert into Address (city, street) values ('Waitara', '1097 Debs Drive');
insert into Address (city, street) values ('Langarūd', '77885 Carioca Pass');
insert into Address (city, street) values ('Lombo Meão', '0 Hoard Court');
insert into Address (city, street) values ('Zhulin', '2 Tony Junction');
insert into Address (city, street) values ('Shaoguan', '97 Grover Terrace');
insert into Address (city, street) values ('E’zhou', '7 Clyde Gallagher Court');
insert into Address (city, street) values ('Barang', '78 Upham Way');
insert into Address (city, street) values ('Likupang', '667 Scofield Drive');
insert into Address (city, street) values ('Burgastai', '5 Delaware Road');
insert into Address (city, street) values ('Chengji', '9590 Wayridge Way');
insert into Address (city, street) values ('Nikolayevsk', '0 Corscot Crossing');
insert into Address (city, street) values ('Karlskoga', '80360 Portage Pass');
insert into Address (city, street) values ('Yakovlevskoye', '1 Hallows Parkway');
insert into Address (city, street) values ('Masape', '4313 Hintze Drive');
insert into Address (city, street) values ('Narvacan', '9 Springview Trail');

-- UZUPELNIENIE TABELI PERSON
insert into person (name, age, address_id) values ('Toiboid', 22, 1);
insert into person (name, age, address_id) values ('David', 40, 2);
insert into person (name, age, address_id) values ('Dunstan', 95, 3);
insert into person (name, age, address_id) values ('Pascal', 46, 4);
insert into person (name, age, address_id) values ('Jimmy', 25, 5);
insert into person (name, age, address_id) values ('Patricia', 44, 6);
insert into person (name, age, address_id) values ('Urbanus', 83, 7);
insert into person (name, age, address_id) values ('Silvan', 90, 8);
insert into person (name, age, address_id) values ('Lowe', 20, 9);
insert into person (name, age, address_id) values ('Lilian', 94, 10);
insert into person (name, age, address_id) values ('Kassey', 81, 11);
insert into person (name, age, address_id) values ('Richmond', 27, 12);
insert into person (name, age, address_id) values ('Flore', 35, 13);
insert into person (name, age, address_id) values ('Glen', 81, 14);
insert into person (name, age, address_id) values ('Gilli', 68, 15);
insert into person (name, age, address_id) values ('Cecil', 79, 16);
insert into person (name, age, address_id) values ('Lind', 88, 17);
insert into person (name, age, address_id) values ('Carlo', 80, 18);
insert into person (name, age, address_id) values ('Corney', 77, 19);
insert into person (name, age, address_id) values ('Deb', 34, 20);
insert into person (name, age, address_id) values ('Dukie', 90, 21);
insert into person (name, age, address_id) values ('Conrad', 70, 22);
insert into person (name, age, address_id) values ('Nelli', 64, 23);
insert into person (name, age, address_id) values ('Nahum', 43, 24);
insert into person (name, age, address_id) values ('Ina', 37, 25);
insert into person (name, age, address_id) values ('Scotti', 94, 26);
insert into person (name, age, address_id) values ('Boy', 60, 27);
insert into person (name, age, address_id) values ('Cybil', 73, 28);
insert into person (name, age, address_id) values ('Benjamin', 96, 29);
insert into person (name, age, address_id) values ('Edan', 70, 30);
insert into person (name, age, address_id) values ('Becca', 56, 31);
insert into person (name, age, address_id) values ('Albertina', 92, 32);
insert into person (name, age, address_id) values ('Victoria', 33, 33);
insert into person (name, age, address_id) values ('Seamus', 57, 34);
insert into person (name, age, address_id) values ('Cinderella', 99, 35);
insert into person (name, age, address_id) values ('Odessa', 68, 36);
insert into person (name, age, address_id) values ('Perla', 64, 37);
insert into person (name, age, address_id) values ('Dianna', 78, 38);
insert into person (name, age, address_id) values ('Madalyn', 39, 39);
insert into person (name, age, address_id) values ('Laurel', 35, 40);
insert into person (name, age, address_id) values ('Maxy', 43, 41);
insert into person (name, age, address_id) values ('Maximilien', 41, 42);
insert into person (name, age, address_id) values ('Itch', 31, 43);
insert into person (name, age, address_id) values ('Iosep', 69, 44);
insert into person (name, age, address_id) values ('Ranna', 87, 45);
insert into person (name, age, address_id) values ('Woodman', 18, 46);
insert into person (name, age, address_id) values ('Brockie', 20, 47);
insert into person (name, age, address_id) values ('Lise', 80, 48);
insert into person (name, age, address_id) values ('Torrey', 45, 49);
insert into person (name, age, address_id) values ('Aloisia', 20, 50);
insert into person (name, age, address_id) values ('Nell', 27, 51);
insert into person (name, age, address_id) values ('Roxie', 92, 52);
insert into person (name, age, address_id) values ('Jephthah', 93, 53);
insert into person (name, age, address_id) values ('Maynord', 20, 54);

-- UZUPELNIENIE TABELI INTEREST
insert into Interest (interest_type) values ('IT');
insert into Interest (interest_type) values ('Cars');
insert into Interest (interest_type) values ('Running');
insert into Interest (interest_type) values ('Cycling');
insert into Interest (interest_type) values ('Singing');
insert into Interest (interest_type) values ('Sleeping');
insert into Interest (interest_type) values ('Motorbikes');

-- UZUPELNIENIE TABELI PERSON_INTEREST
insert into Person_Interest (person_id, interest_id) values (1,1);
insert into Person_Interest (person_id, interest_id) values (2,1);
insert into Person_Interest (person_id, interest_id) values (2,2);
insert into Person_Interest (person_id, interest_id) values (2,3);
insert into Person_Interest (person_id, interest_id) values (5,2);
insert into Person_Interest (person_id, interest_id) values (6,6);
insert into Person_Interest (person_id, interest_id) values (7,7);

-- UZUPELNIENIE TABELI CAR
insert into car (brand, production_year, person_id) values ('Cadillac', 2005, 10);
insert into car (brand, production_year, person_id) values ('Maserati', 2004, 17);
insert into car (brand, production_year, person_id) values ('Buick', 1999, 17);
insert into car (brand, production_year, person_id) values ('Chevrolet', 2007, 4);
insert into car (brand, production_year, person_id) values ('Hyundai', 1998, 14);
insert into car (brand, production_year, person_id) values ('Mercedes-Benz', 1992, 14);
insert into car (brand, production_year, person_id) values ('Plymouth', 1994, 14);
insert into car (brand, production_year, person_id) values ('Dodge', 1999, 17);
insert into car (brand, production_year, person_id) values ('Mercury', 1997, 12);
insert into car (brand, production_year, person_id) values ('Mercedes-Benz', 1989, 8);
insert into car (brand, production_year, person_id) values ('Mercedes-Benz', 2001, 14);
insert into car (brand, production_year, person_id) values ('Ford', 1983, 2);
insert into car (brand, production_year, person_id) values ('Lexus', 2009, 19);
insert into car (brand, production_year, person_id) values ('Isuzu', 1994, 15);
insert into car (brand, production_year, person_id) values ('BMW', 2005, 9);
insert into car (brand, production_year, person_id) values ('Lexus', 2011, 7);
insert into car (brand, production_year, person_id) values ('Pontiac', 1987, 10);
insert into car (brand, production_year, person_id) values ('Volvo', 2003, 10);
insert into car (brand, production_year, person_id) values ('Honda', 2001, 8);
insert into car (brand, production_year, person_id) values ('Volkswagen', 2000, 16);
insert into car (brand, production_year, person_id) values ('Ford', 1998, 8);
insert into car (brand, production_year, person_id) values ('Nissan', 2008, 5);
insert into car (brand, production_year, person_id) values ('Audi', 1995, 18);
insert into car (brand, production_year, person_id) values ('Isuzu', 1994, 17);
insert into car (brand, production_year, person_id) values ('Subaru', 1995, 18);
insert into car (brand, production_year, person_id) values ('Mercury', 1987, 7);
insert into car (brand, production_year, person_id) values ('GMC', 2000, 7);
insert into car (brand, production_year, person_id) values ('Chevrolet', 2002, 9);
insert into car (brand, production_year, person_id) values ('Buick', 2010, 9);
insert into car (brand, production_year, person_id) values ('Volkswagen', 1993, 2);

