-- UZUPELNIENIE TABELI PERSON
insert into person (name, age) values ('Toiboid', 22);
insert into person (name, age) values ('David', 40);
insert into person (name, age) values ('Dunstan', 95);
insert into person (name, age) values ('Pascal', 46);
insert into person (name, age) values ('Jimmy', 25);
insert into person (name, age) values ('Patricia', 44);
insert into person (name, age) values ('Urbanus', 83);
insert into person (name, age) values ('Silvan', 90);
insert into person (name, age) values ('Lowe', 20);
insert into person (name, age) values ('Lilian', 94);
insert into person (name, age) values ('Kassey', 81);
insert into person (name, age) values ('Richmond', 27);
insert into person (name, age) values ('Flore', 35);
insert into person (name, age) values ('Glen', 81);
insert into person (name, age) values ('Gilli', 68);
insert into person (name, age) values ('Cecil', 79);
insert into person (name, age) values ('Lind', 88);
insert into person (name, age) values ('Carlo', 80);
insert into person (name, age) values ('Corney', 77);
insert into person (name, age) values ('Deb', 34);
insert into person (name, age) values ('Dukie', 90);
insert into person (name, age) values ('Conrad', 70);
insert into person (name, age) values ('Nelli', 64);
insert into person (name, age) values ('Nahum', 43);
insert into person (name, age) values ('Ina', 37);
insert into person (name, age) values ('Scotti', 94);
insert into person (name, age) values ('Boy', 60);
insert into person (name, age) values ('Cybil', 73);
insert into person (name, age) values ('Benjamin', 96);
insert into person (name, age) values ('Edan', 70);
insert into person (name, age) values ('Becca', 56);
insert into person (name, age) values ('Albertina', 92);
insert into person (name, age) values ('Victoria', 33);
insert into person (name, age) values ('Seamus', 57);
insert into person (name, age) values ('Cinderella', 99);
insert into person (name, age) values ('Odessa', 68);
insert into person (name, age) values ('Perla', 64);
insert into person (name, age) values ('Dianna', 78);
insert into person (name, age) values ('Madalyn', 39);
insert into person (name, age) values ('Laurel', 35);
insert into person (name, age) values ('Maxy', 43);
insert into person (name, age) values ('Maximilien', 41);
insert into person (name, age) values ('Itch', 31);
insert into person (name, age) values ('Iosep', 69);
insert into person (name, age) values ('Ranna', 87);
insert into person (name, age) values ('Woodman', 18);
insert into person (name, age) values ('Brockie', 20);
insert into person (name, age) values ('Lise', 80);
insert into person (name, age) values ('Torrey', 45);
insert into person (name, age) values ('Aloisia', 20);
insert into person (name, age) values ('Nell', 27);
insert into person (name, age) values ('Roxie', 92);
insert into person (name, age) values ('Jephthah', 93);
insert into person (name, age) values ('Maynord', 20);

-- UZUPELNIENIE TABELI CAR
insert into car (brand, production_year, person_id) values ('Cadillac', 2005, 10);
insert into car (brand, production_year, person_id) values ('Maserati', 2004, 17);
insert into car (brand, production_year, person_id) values ('Buick', 1999, 17);
insert into car (brand, production_year, person_id) values ('Chevrolet', 2007, 4);
insert into car (brand, production_year, person_id) values ('Hyundai', 1998, 14);
insert into car (brand, production_year, person_id) values ('Mercedes-Benz', 1992, 14);
insert into car (brand, production_year, person_id) values ('Plymouth', 1994, 14);
insert into car (brand, production_year, person_id) values ('Dodge', 1999, 17);
insert into car (brand, production_year, person_id) values ('Mercury', 1997, 12);
insert into car (brand, production_year, person_id) values ('Mercedes-Benz', 1989, 8);
insert into car (brand, production_year, person_id) values ('Mercedes-Benz', 2001, 14);
insert into car (brand, production_year, person_id) values ('Ford', 1983, 2);
insert into car (brand, production_year, person_id) values ('Lexus', 2009, 19);
insert into car (brand, production_year, person_id) values ('Isuzu', 1994, 15);
insert into car (brand, production_year, person_id) values ('BMW', 2005, 9);
insert into car (brand, production_year, person_id) values ('Lexus', 2011, 7);
insert into car (brand, production_year, person_id) values ('Pontiac', 1987, 10);
insert into car (brand, production_year, person_id) values ('Volvo', 2003, 10);
insert into car (brand, production_year, person_id) values ('Honda', 2001, 8);
insert into car (brand, production_year, person_id) values ('Volkswagen', 2000, 16);
insert into car (brand, production_year, person_id) values ('Ford', 1998, 8);
insert into car (brand, production_year, person_id) values ('Nissan', 2008, 5);
insert into car (brand, production_year, person_id) values ('Audi', 1995, 18);
insert into car (brand, production_year, person_id) values ('Isuzu', 1994, 17);
insert into car (brand, production_year, person_id) values ('Subaru', 1995, 18);
insert into car (brand, production_year, person_id) values ('Mercury', 1987, 7);
insert into car (brand, production_year, person_id) values ('GMC', 2000, 7);
insert into car (brand, production_year, person_id) values ('Chevrolet', 2002, 9);
insert into car (brand, production_year, person_id) values ('Buick', 2010, 9);
insert into car (brand, production_year, person_id) values ('Volkswagen', 1993, 2);